---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAbUpj8ufCx8r8OAwqxbt+AZFtOYKNu9zvgvbx6OJLEUPO81wyLkuwBLc8hud8ogVhvk4a6MA87+ceBd1AcM8HWbn7azY9eW4Zou9+ikPSJMxE36EOJpaWchEaIQNr1ZlQ8J0jWxoXBQZINF14NoWN/IZSSr3vgbVJNwT5eEblOt14iDVRGDPh8b+DGQuprxl5fejwpKnAjHnZz0a29Gpi3YK1rT7T50ou+Ks/dH7wN3+2Rp0jfMxlxxDbOwEjtUMhO+kMItorod7f9Pfos6Ab0Gh3pQO0B/xr0nrVvU8Ib8XJC11zcekPWAHNkdB/Ltzv5lC1UYqA47qWTFF+fDZ9kRmY5shcHZUwglrvcVE9n7DcxvzzFv7+8+h4WZXEJ9SRW0FTe34ROOWXzcxcTPba/wKyosFoBEZE/5XNX7IPbM7xPNi6A6z08nATtMN/o99WDkOUrQbCMunHxGJfVTQ+KPrNJ5Nu6SzD9FtVYae6VGJDOF4nSBDEqVXJsAhfLbVxhF6hjOBBo1UQ7xnJ3z67Ps5mWzIFKVXJ7ufdSCN2tGTlcBjP+Vj1PUKAXl0VjvW/lAaV/AckMsWD+SEar46zTrdRBibvJHhg77XCMQvfbfJp+LD/X77znzXUVYnkJy+7dj5r3guvd3gDmRyf9qRaMnhR2ZeLm6ygxc4PSt83bQCpuv/r8larLxKsWz2YOd8wJigiBxIuLWckcOJhZjRaQzkfe962oEkg5Krr0nPdHDj+p0FCZ5y+t/zeJejX8/O8N1FzMA6m2iJSc04/73k8+
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
