servarr:
  jellyfin:
    extraVolumes:
      # Errored streams build this cache up to the point of filling any pvc. This way k8s will kill the pod if it uses up all this cache and we don't persist garbage in a pvc
      - name: transcode-cache
        emptyDir:
          sizeLimit: 5Gi
    extraVolumeMounts:
      - name: transcode-cache
        mountPath: /config/cache/transcodes
    persistence:
      media:
        size: 100Gi
        accessMode: ReadWriteMany
    tailscale:
      enabled: false
  sonarr:
    env:
      TZ: America/New_York
  prowlarr:
    env:
      TZ: America/New_York
  bazarr:
    env:
      TZ: America/New_York
  radarr:
    env:
      TZ: America/New_York
  lidarr:
    env:
      TZ: America/New_York
  seerr:
    podSecurityContext:
      fsGroup: 1000
  qbittorrent:
    env:
      TZ: America/New_York
    persistence:
      additionalVolumes:
        - name: custom-scripts
          configMap:
            name: qbittorrent-custom-scripts
            defaultMode: 0755
        - name: qbittorrent-secrets
          secret:
            secretName: qbittorrent-credentials
      additionalMounts:
        - name: custom-scripts
          mountPath: /custom-cont-init.d
          readOnly: true
        - name: qbittorrent-secrets
          mountPath: /var/secrets/qbittorrent
          readOnly: true
