apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: servarr
spec:
  parentRefs:
    - name: eg-public
      namespace: envoy-gateway-system
      sectionName: https-public
  hostnames:
    - "jellyfin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-jellyfin
          port: 8096
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr
  namespace: servarr
spec:
  parentRefs:
    - name: eg-private
      namespace: envoy-gateway-system
      sectionName: https-admin
  hostnames:
    - "seerr.admin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-seerr
          port: 5055
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prowlarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg-private
      namespace: envoy-gateway-system
      sectionName: https-admin
  hostnames:
    - "prowlarr.admin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-prowlarr
          port: 9696
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg-private
      namespace: envoy-gateway-system
      sectionName: https-admin
  hostnames:
    - "sonarr.admin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-sonarr
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg-private
      namespace: envoy-gateway-system
      sectionName: https-admin
  hostnames:
    - "radarr.admin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-radarr
          port: 7878
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: servarr
spec:
  parentRefs:
    - name: eg-private
      namespace: envoy-gateway-system
      sectionName: https-admin
  hostnames:
    - "qbittorrent.admin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-qbittorrent-web
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bazarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg-private
      namespace: envoy-gateway-system
      sectionName: https-admin
  hostnames:
    - "bazarr.admin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-bazarr
          port: 6767
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lidarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg-private
      namespace: envoy-gateway-system
      sectionName: https-admin
  hostnames:
    - "lidarr.admin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-lidarr
          port: 8686
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: qbittorrent-bt
  namespace: servarr
spec:
  parentRefs:
    - name: eg-public
      namespace: envoy-gateway-system
      sectionName: tcp-qbittorrent
  rules:
    - backendRefs:
        - name: servarr-qbittorrent-bt
          port: 6881
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: qbittorrent-bt-udp
  namespace: servarr
spec:
  parentRefs:
    - name: eg-public
      namespace: envoy-gateway-system
      sectionName: udp-qbittorrent
  rules:
    - backendRefs:
        - name: servarr-qbittorrent-bt
          port: 6881
