apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: servarr
  namespace: servarr
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: envoy-gateway-system
