---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: recyclarr-api-keys
  namespace: servarr
spec:
  encryptedData:
    RADARR_API_KEY: AgCRjKhw/0Ysh0ku9labOwqTJekT6piL8+YrW6j+Q75oDjmimXJRv4RVsdONzIi5afit7PmbFxCZBt17hF5T0jkqNHm0mrdj68c7eBAwV/FrIvDMic/OjIZPQ4rn3VpP+A2kBILbKtVj8Zds+dIr/qHzk+u515OU/PzPCHecM1oy0cJS+vdc5HngyZcpDMNi8+d0BcwlO2IdV54efUQm2DDcQRsk03V9gD0J+TLcXR7bOinYUEwpjkUuFd5M71jpbB/AAfFcp6I2Bu5xnhUMajVRZabqSqSYzw2Rl6F6+3EzYpA3606V89K6/3ze2PEbr6p8o7oqTZZFXVcFnIN2ZqQZ69sXJ1Se8HtvAj+Lujka2MiV+28/UGYO+KOOqteQeoLDJbfj9E5eKKFeOj1v58blpSNqLLn3a1CfChbK87cAoDANNgacmyt92pbFNrKC4WO/X4L9TWguJOPh3EtC7C4qOe94vMJjkZsB9K46m6mdKd1ZKJ2HkPy6POr7JsASdPF/Xjxrn9lKkxXLfSZPcteNRGg0F1aFri9pkmklljqvAsgMhrbNS5sBo/nk3mV7JKcIbKjeeyeqOzgqls7UxUSGvIWKC3Im8FOyRJRayvclut7gxOBtY2laAYNBx8LC87NFI/YWpqJwhfDY0ZM/5MkOUnh39To5ZYdNz+32d5g+q73TKdVRrBxto5d4VUmxHCe7T7cUr8lT7a64eR/b2V2ZIXaFwk3p/NbRZQfXbxvo4Q==
    SONARR_API_KEY: AgBZkgbzels9vAxcixRz5P9HHZ0EnPBvaezYghmD9S0cVGWxAQkMF6QZIIsrb3FgvkbFgO2K1I8sTHHHqR2ea36TnOWMHmCxmvn2j2cJeM2R6nsl4xsUC6m3sYsx7Qo22KOMVnSGx5tQLa1D4U/C/DV/aXeoSzsPC6onvYwV+4CoRkGCKwBX2XYs98/KYDZ3nM9PRa5RgTJ5DM5zZueaYPW0Bi1Tf74nWVbJDuIUWrFLTdjnIhAreIeRA95du4+BnH4VdCGW/fE/7G1eFfTjPYOhL0rNsg5INVs8CKNkBFJn4YlEQTFg/3CBBxA6DKnA1BrWUfKLUn6s1er83SoJskHmMB3Y7Pd7MpvD9MvrcOPGKZ1ocr1vPnwd0ScLa6EGl00u+EDwp5QB16eLUkN79Yj7+Cxhsa/FXsxDhxw7XfB3IEG+ly8FeopFa8fyl5Yb4DoHX/TTXjjfJgoHz/UVwOlp9ZUJ48dzlUEYJl4YWmzvrbHuLtvnvjmICRbIKkU6nK7Vd7Ylv6SLBjGrJPdHJUtG4cG6lCXLl1OVlzplmsD1XY72J8bvxmRcenIMduxBdB5ybh4Kad0woezfL6XFes8lVyOgDsu9OJxHU8OdX9E4W0XCSwNen9D9riuORiN59crz7O5CKiIkBttCsI+IMm/w+MfKm5PniWy55yO0/fQhnoQJZhQpE+4350bOL5GsYG8gzQyCi1quqGJG5qxYHZaQw2B49rwsqkxNfZEBtBBmQg==
  template:
    metadata:
      creationTimestamp: null
      name: recyclarr-api-keys
      namespace: servarr
