apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: envoy-gateway-system
