---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jwt-secret
  namespace: expense-splitter
spec:
  encryptedData:
    JWT_SECRET: AgBX4aU5tzBYMlp8CISWRufcDDEPXZYfQIGoX44HQbQ9ATUeqb+qGbb41TTYEuOksU93FPp11RzhC8llQT1X3ToNrQiK25EM+G7vI2hsQRjAG1mLSGfm4OG5PmZMxCQPvWaZ6FCy0q/5AlZesvQSvQXTFPXk5IYswtl93GInk51PaWk+N2+54kC5OzB3ukVmUeMu52CJ6T9IfuY1aGwemAdMWntHRYQ1fIuauzv8G4lJTCgZAugSkUVMm3JMWXfGGh5WoEfXIYT/EVYHIU3qKh4utCOtzqKq8vR1GHPbeVsKtfHTp4Ei+oLCo53xj67nSn9xIDxUKKbrScdUXYDsZORPwupX5uhRSYAnblELaOHci5xbQbIIYRGw1VpRui/9G8kIQmYXlhVVxrtztJJRvxolBf+rZtLdZEiwnwJ9xRi2WGs5LZWMhyFve1Kd3Oz3olvOylqDRO9Wl2QoBPEod1/UgjC3gH71CD4ApMR6bUndcJcS2TjxxotwfbTWiOvv0xdzj1W9dnfeYsN39QU9umO2f8OU+Y/bZiMeusDf9fcRedaNGXsTPagFi0GvQCOjrmQJ0qIz2arYwhHunjQl56zb1GthHcMaEo/HIXjA8ZMGs256VoEEI/12dc2BLqvOkKkVFdULeuLtyJgAXu8XYdc5YHspsjxaUqIF+wBqBKLXJBGwwc/zy6uZjr/FZP75PdvAhlUQ3o4gaz5QRwzQG5FvN1cPX3qC2W8SMXPHGUnJZCRkfGr/l9uAAquH9A==
  template:
    metadata:
      creationTimestamp: null
      name: jwt-secret
      namespace: expense-splitter
