---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gha-github-pat
  namespace: gha
spec:
  encryptedData:
    github_token: AgBGhYmrVjLXblXEo0n6/Eo8wsU832RmFmT0YewMvJNofOZRI/krQvryWylLLO6V95IPrWDsBJttXp6NLf2UP/PLtepm0XVKyLJjpdQ2ZFNe+4gqKWdyvxG3kjWSuyCZZM0p5m7dSsC7iwDGCGCzrQ5PIgM1sMQ6xyGfRhZpSlShagdbDz4BcxxteUik4sYtf2hVpmKp4d5WXGJH0Gf8G5p99Y0J5OyJIH4//Z2yRLkwN2+F/ECHNUWrMD5UnghiR6e1ZJIsuX/tfG8TV0I+2wodhPlv8IJbGIwbCbwzXMvbqYAC5DhPjq+VtGtxYlwbZyoIVgohT0ON6/I9R0j7rJsI4nvEqvy+y2dPhLbOc6ikUprMVJ/Hhk36En83I6hExZhTU/ZWGu7hSYCmLuJDtgS51vr+k9NyJjSlziksAt+bQDd41B5kOFX+JghV7nGeXF8BbcU0wT+VnAIjyrJctG3ocwb77YjVRnwRzBJDmr6oy0K3BWZFo1hrRMtBQYPSTDNi7KADbcqs948xTrCM9CSGgcvQrzBcWuY6AHn+mKfcYkX44ET0IOElbwZdAHyZ1V6cFOuODXFZKjUDyEu+L0yfiSBBGi9KCdhWmVffXpOBH/QTKvmgAcSPaNifECHZnQn1bCqWwLWqsrVHrnZX59XsZnW7vakikB7KMaHHrw/aWxHemfFraPtkyOc7BDpB8nFvl3X4EC6yNBTEiFB//GWXBEMtfQ1r4+rcSVKO3Ivcq77cUb0t2SvF
  template:
    metadata:
      creationTimestamp: null
      name: gha-github-pat
      namespace: gha
