apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent
  namespace: hermes-agent
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/hermes-snapshot: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
