apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: docker.io/favonia/cloudflare-ddns:1.15.1
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token
                  key: api-token
            - name: DOMAINS
              value: "michaelmuzafarov.dev,*.michaelmuzafarov.dev"
            - name: PROXIED
              value: "false"
            - name: IP6_PROVIDER
              value: "none"
