---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cloudflare-ddns
spec:
  encryptedData:
    api-token: AgBH9Eg3suOyIDDx/Hwhrr77VsFyWZhYG4oMcc7YsQ269PhtLSXePe12bzQjSqk3ZtKFf8IuAj8S9dq+Kz9eZFjHe5a6br1Wxj+cjWi57KkW1rcxjtWC5ZCJk4mwHipPE4r11aTYIVnYZrZraj58TZ0FZGnnwj1IafjY61s5x0DRZjNB7CWHsbdDSkLSJe+dZJSAfRsjX8zsLLuyIgVMwZs7/CxFp7xdFZw9NIe19WX8nTrGauo3xIKdoHp5KwScUF26L1MSE9teXe0VuWmF3ioArfPY2ovXsimQTyPPz25fgRYHacX+P8qStPzVDeFhT00uqemsdF85HA3PVw3v982rAjZiQQWmbUOzCfJtnW9+b89lcPTuXYNmpuFTkSYx5n0hs3Umm/QPdn1nTN/dNCSlVwp/BMZkw8IB1QcF9Vql+Q/YB+SLCk9hSibT09nMeEn0F3yhehsW3tNOb46yVTvr8uFXw1iM4dP0rQwsrqGYsL5PGuBn5aBPt12xS99iUDRCcguCnxB5jI9wanVVrSc8TBpxYAFtkrhHLhJiSHrMr6EGglBe2ktijk04RoAqtT/Y9e55L7Ru67R9J5LB0O3co0Z2pVXwPts9HWwpP6Hc/S/hRjUcdtMDJ/uTlitBZxRIgrpt32HPQEnWBkEfFdMDpNczAvS73dw23AgOzQYt2DK6gdMRyQceZYlNgQa25qmHIc20uBazrC/mnL6Svl0RJqVrVYL6eNMIGH7SF36AeKEPvDkqlveL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cloudflare-ddns
