---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCd2S6d6dlttlqPWhKg/3320+DtsJqMOkgbpbj+QA57FrvxPVfSUwZesneHxYeOgOPc2LJJZ5rjgPweD0csl5oLNebC9irCgUrTXRua2Wo0cWV4x/7Hk+57LB4m1f+OREkyp8R5IhAhhJ1vM5xLGH3eFFb3TdDTG37Q5jUoI2n2qGLPVlCMrdR5wAeoAFL8mGo8ArgRuH1v8faV29+Zw0Rvy7Tl47dOxolMlZuICd6A51rjembC3lVgwF4aXWErx42LtLrEE7n2miRiycuNbHNvMUnP4xSGF1vofa/S8o+n/eiGtsNTmbC7HgqQVE4rKkRGHYxePP+5p6DbC4s05OVkfVMb92hF/sSOMftaDH7lvuG5u2FJCOCouNXN5fKBoysdd2hS7Dnqxrb4aEOoM4Mc0L/NXGnKD3YMkNWJ/mXG6401OJzFH20ap20rB7Ags44q2tr+97oEy+sL16LqGXxXKp0ZGDQgO3aeqjrtPcu2h8u5Q25GkhnBNZfmxcsubfZ5Qq8cX2mjlgBldyw3NqAGB3/Y+Ca5ff05jVPnaBuI6Ie5KqQBGFqjZTfeqFpNuyvNh5DnsE8MYcrw/BIK+A4/CA+8xPw/X40+arfffuF8JD8jkfSPk4osI68a4Ne0VLNdBNxR5zrBnDRqjU9bJ25pO09iVJfg89umTNPXrSUAWtDu+79C8VRv6fnFRRHcr9UprxbJkviJ9kJdvA==
    admin-user: AgAlt65K78KKeK4Rly91fEe8x4K1WxZ3VTPEC6AJf7y837kzMuDUEUe6ntzcd7pjbqBtCOIQM4tUP0fAFMOBej+s3vn36YJ/q1dgtnldctFzk1DpWQcfqYA3G8vgZpgSJ6aPpYW6+IV1vYCN5GCOIbtktad5IzDiAgybKKPkBLThHa2GuTeujVtcahB0Gv9Uo8rJpOagCbkq4xlfZ+yu6CNIaivEbSN/T5/OQcjjPDonMJnTxqgYhAinSqzm4c4WDCCrPWUy6zUkKH5FXdRCpH7XO+j4wZBi13l+3R4j/DMBzEIS7XiVPNcPORwb6UMfVK9UvFuSnOmU4zfq7YCIDVGqmCV0+ePFG0K6TsDQEWpt3j0YYNPlOM3fw88tSKZw44EcJih1Su/G9tXu3on/+D+Z7k9PwR0cyA+M36QYnQW0QKiRn0UYdEqI423+7o3dzzXgAMePFcR9Cj30/qBpaLoWRhUIA9JMyGgJs8lAVPw2ruLKEgmT/jBXsEmoeBivldzn70Uy1gvPr+o/43GjaTYrChJOJhJUwvLq+qtIEN6nrJcpO1XOxemDOI+VqIglbTwlgmAZ0H2OvciLTCnma2+hCS4htR+5nGLNTxOkkD9EZdlgmnSQH1VAcsMHFFR0/zIQMUA/F5BgZSVCluiyARYcK0pDHgGYTRiPnvTbtTNHSXwcFlPiX/ICLOfastPQy8v1escRzg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
