---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  encryptedData:
    secret-key: AgCs1l6M2cn7N6xK+ky62QDaWFpLK+a3atssQKAvAAFn8pg05xUQl41RQWc8S5lhKmkwP0IV8VvotcLhLNVfHHyW6qI6CMEEkprpEzWQ1G7+xwr7sR+CSA4jZqhivUGck8ApqvjckRC31xbX6FLWCWk/UTh0LzDaPRhZU3ljckOmXWcEEgGS3LMParvxP/8EjIzj46qOHFlKcMd68euxannIRWYlqAzhQzfbHu9S8XVW6kqGAPZIMzbKRjszDcEmCwLGhFs7/SRmpGQW3YtCNvCGJTX+C/ff23u6jQpqjVl0DTyfXFt0b9LB8RENgB4pwhhBPf/ZrHedvMXc03pKqGgvELq1l1NCeFyVkkBXR2R7+XejiPfR+HfKjzb+TyLPs2EVJldL8RVMV/iwrHCPd6Q80evWMTk1WcOrXdPf0E8Ue5JQUI55KuqRNZcsvoPvaHIV7RREDPN3ss/nxDqR1ODIfHZXLuHKEX8LG6OWPJCyfNnstkb6Gf6XBbr0Y1TaQQJB5RYJqqOL9o8BcK0ocJaAHIKrzb2cJclYrV7cadMV4oJ2z3/JUpEKx4mniaqxBEIgRuWHieNDpqn42OnIS0C5jnuF5rYHKOPE7isJ8J/P3QkEJeC8LM7ND5Z0X+ioG9Sd3bVRQEPujOh9FGzUXt3onBHDnIiVWH1eyNfsozW3GoPPqtmZb5eEV9JFhSxIvJ0fyEbzVYgWX1cHR2LkqQ3jxOJJdu5LvkuI9c2R1AoT5m/lImLDeSHCOQNmCPs69ga6NkfTFv/1KVrYC6LcuP0w
  template:
    metadata:
      name: searxng-secret
      namespace: searxng
