applications:
  - name: longhorn
    namespace: longhorn-system
  - name: metallb
    namespace: metallb-system
  - name: dns
    namespace: dns
  - name: argocd
    namespace: argocd
  - name: sealed-secrets
    namespace: sealed-secrets
  - name: cloudnative-pg
    namespace: cnpg-system
    serverSideApply: true # otherwise metadata annotations too long
  - name: tailscale
    namespace: tailscale-system
  - name: monitoring
    namespace: monitoring
    serverSideApply: true # otherwise crd metadata annotations too long
  - name: homepage
    namespace: homepage
  - name: searxng
    namespace: searxng
  - name: servarr
    namespace: servarr
  - name: immich
    namespace: immich
  - name: cert-manager
    namespace: cert-manager
  - name: cloudflare-ddns
    namespace: cloudflare-ddns
  - name: envoy-gateway
    namespace: envoy-gateway-system
    serverSideApply: true # otherwise crd metadata annotations too long
  - name: cilium
    namespace: kube-system
    serverSideApply: true
  - name: gha
    namespace: gha
    serverSideApply: true
  - name: renovate
    namespace: renovate
  - name: expense-splitter
    namespace: expense-splitter
    continuousDelivery:
      - name: backend
        image: ghcr.io/michaelmuz/expense-splitter-backend
        tag: latest
      - name: frontend
        image: ghcr.io/michaelmuz/expense-splitter-frontend
        tag: latest
  - name: hermes-agent
    namespace: hermes-agent
  - name: blog
    namespace: blog
    continuousDelivery:
      - name: site
        image: ghcr.io/michaelmuz/blog
        tag: latest
  - name: quiz
    namespace: quiz
    continuousDelivery:
      - name: quiz
        image: ghcr.io/michaelmuz/quiz
        tag: latest
  - name: blue-bubbles
    namespace: blue-bubbles
    continuousDelivery:
      - name: ingest
        image: ghcr.io/michaelmuz/blue-bubbles-ingest
        tag: latest
  - name: n8n
    namespace: n8n
