---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAopd5bXyaQ+Hzq+e4vLnp+qa/AKS0FVNBPnU34QhQlKMDDzAl0o24ESx0cHnGz2TW1HsWiKpeNnMfDdpvkJAwoNLMwQTa8lJPP36UzyIr+FZ9yEX3+zRHI4YEyEeibAXsvbVp5GTJGzFraXIKyhoerxMtE6qkJGdctJoR+5OVLDg4g4tG/aKUHbSGS2BmMlMeVa6QJaakUD2IVT1W1zDCOOgkpdn++dJDLwmMobQoQHXpZ94YKFV86lYjR59uS0ugMXhNjkiVV54OE5jEA6v5aBIjkfQZLaEnXgfCzug0ZtmZ0ftb6ThN7bV+KPiXpgGhaeI030LTb52Ebx1S7tQ4DyRdHYCMeoKo8sSgzIi0fDgQtf6pMXC+mhQC4R+hTUHAHwMMEWo6ZJq//usIO97K+JuE0wNjmYUct7OPwxc8j+Fjg3dyCVW3VGAGoaIpHNuxrfY6nIv1PKL7kn2O+VqEWMzRFXCnnfL1okoIKss058Z0pGG++I90jA0hE1Zp1GmgvAyCeKMFzQpNasiCk4fELG0ENOfskIkfUs71HrcsEVpwookdf3PPmCySMrk/VuQDI4R1bX0ei4Bhk6dryoP6NR1bEuAb3l65Ee2QmsOeikVujYkRpAZWc1ktIYr0yN4bu/wbhoaemN8Uat5hZ7/kfJhlvCeZ1gv2fsLbiw3yFD3u4ZD4FlrF67Ey9sJr3I3FL/SfYzFh2iw0Z3Bk5wkFosukN6YxFXP5uxLzOrSDevJTJsPer51ksiRW6tEd1Yf4cJuraTahPI0wXoKYr6ENCxeA1yZIK5i/pHMAoetilUTNb5coKk0FfSBSVaPc=
    RENOVATE_TOKEN: AgB+jU+hdxSkCbfOl2KIUfkKJ9M+H/4jvq80H5TsAWgO9Hzp8Z4wS+S50ZMBNJbbXthHxAIyXVSB6YYDXe66duke8Do+MEuR7NxBFRwkwef1vGP4BoPmCS5BLl6KIE4PtoF2qo0qt78YIo/LFSC9tahItKQqMKxyTabtF9yfcQOjcrjlcF3f4UxcyhRpIFYKrD8jaTf8TlgBHGH8pFCVOHx1euFRBHyELfk0E3Nj9VsCZE0bm/hIGbb3urezxkKKL+nv7NHbYwuVmtpkkfzUYFuCmqIr5AKygt5fzkkkxySQ6xHVFhleXQ8k8snUUDzGlNqmq2XZiysx4fh8hzCkfP6eM95exTRN44iX0ytZZqfIjYEy40um+Lcc7m/aXQ7jWaQtqfIwdlaaJmF0YKK0zkLkQ4LCJhxASpl8CoJ8pe0TJtnbOoeVXQunguH13J6NMZoPfKbx+MnfmkBvomA/p5qpPHLUjT2V6Q00ZYPxbDJ43sdSef4skqKNXRkchx5wqtgD+WO49EzfrjziDPBR9w9/Cz0sBFtCjNpzkEhcSULaam7Kv7DfrT0vvNniazerc8bdQZHo4t/ANC46QGrAmKoZzeDOXxC/R+ms0gDU6EkSnTSx8uogpuzMG6oketM3eXnmC2XHtBXC9dv2Kv/lc5gq9sAHPFutCzqzK91QgrtFHijmBK7vR3op0hy82NZc3G/nl/pUMMlbDl7aeKr7f+5PUog6+G/fqrAO7utmwMLUr6LF+dySCjrrpe/SRWadOw3htNTkP6MrxhxCs+pJLw==
  template:
    metadata:
      creationTimestamp: null
      name: renovate-env
      namespace: renovate
